# Generated by Django 4.2 on 2025-01-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
    ]
