# Generated by Django 4.2 on 2025-01-05 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoria_options_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='Categorias',
        ),
        migrations.AlterModelTable(
            name='proveedor',
            table='Proveedores',
        ),
    ]
